<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6380a09426fc2',
	'title' => 'Member Options',
	'fields' => array(
		array(
			'key' => 'field_6380a09425715',
			'label' => 'Job Title',
			'name' => 'member_job',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6380a0ef25717',
			'label' => 'Credentials',
			'name' => 'member_creds',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_6380a0d625716',
			'label' => 'GDC Number',
			'name' => 'member_gdc',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'team',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_64425ea5dbe98',
	'title' => 'Page Options',
	'fields' => array(
		array(
			'key' => 'field_659d3b6a801f8',
			'label' => 'Banner Options',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_64425ed8d59ef',
			'label' => 'Alternative Title',
			'name' => 'banner_alt',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_659d3d18632d9',
			'label' => 'Introduction',
			'name' => 'banner_intro',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_651e83d9933ab',
			'label' => 'Call to actions',
			'name' => 'banner_btn',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_651e8401933ac',
					'label' => 'Button Link',
					'name' => 'banner_btn_link',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_651e83d9933ab',
				),
				array(
					'key' => 'field_651e841d933ad',
					'label' => 'Button Text',
					'name' => 'banner_btn_txt',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_651e83d9933ab',
				),
				array(
					'key' => 'field_657883cd43d8d',
					'label' => 'Button Colour',
					'name' => 'banner_btn_color',
					'aria-label' => '',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'black' => 'Black',
						'accent' => 'Accent',
					),
					'default_value' => 'black',
					'return_format' => 'array',
					'allow_null' => 0,
					'other_choice' => 0,
					'layout' => 'vertical',
					'save_other_choice' => 0,
					'parent_repeater' => 'field_651e83d9933ab',
				),
				array(
					'key' => 'field_651e8443933ae',
					'label' => 'Button Destination',
					'name' => 'banner_btn_destination',
					'aria-label' => '',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'internal' => 'Internal',
						'external' => 'External',
					),
					'default_value' => 'internal',
					'return_format' => 'array',
					'allow_null' => 0,
					'other_choice' => 0,
					'layout' => 'vertical',
					'save_other_choice' => 0,
					'parent_repeater' => 'field_651e83d9933ab',
				),
			),
		),
		array(
			'key' => 'field_659d3b84801f9',
			'label' => 'Quicklink Options',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_654e0a66757e6',
			'label' => 'Alternative Quicklink Title',
			'name' => 'quicklink_alt_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6597e43fe0646',
			'label' => 'Alternative Quicklink Image',
			'name' => 'quicklink_alt_img',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_654e09e9ac846',
			'label' => 'Alternative Quicklink Button Text',
			'name' => 'quicklink_btn_text',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'treatments',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6373bbcf054cd',
	'title' => 'Page Sections',
	'fields' => array(
		array(
			'key' => 'field_6373bbcf381ef',
			'label' => 'Sections',
			'name' => 'page_sections',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => 'field_6373bc16381f0',
			'button_label' => 'Add Section',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6373bc16381f0',
					'label' => 'Choose Section',
					'name' => 'choose_section',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'split' => 'Split Section',
						'quicklinks' => 'Quicklinks Section',
						'accordion' => 'Accordion Section',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_6373bbcf381ef',
				),
				array(
					'key' => 'field_65733f45e8e39',
					'label' => 'Split Section',
					'name' => 'split_section',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6373bc16381f0',
								'operator' => '==',
								'value' => 'split',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_65733f46e8e3a',
							'label' => 'Hide Section?',
							'name' => 'split_hide',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_6576f1724822f',
							'label' => 'Spacing',
							'name' => 'split_spacing',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								't' => 'Padding Top',
								'b' => 'Padding Bottom',
							),
							'default_value' => array(
								0 => 't',
								1 => 'b',
							),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 1,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
						),
						array(
							'key' => 'field_65733f46e8e3b',
							'label' => 'Background Colour',
							'name' => 'split_bg',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => 'Deselect option for white background',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'white' => 'White',
								'grey' => 'Grey',
							),
							'default_value' => 'white',
							'return_format' => 'array',
							'allow_null' => 1,
							'other_choice' => 0,
							'layout' => 'vertical',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_65733f46e8e3c',
							'label' => 'Media Location',
							'name' => 'split_location',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'left' => 'Left',
								'right' => 'Right',
							),
							'default_value' => 'left',
							'return_format' => 'array',
							'allow_null' => 0,
							'other_choice' => 0,
							'layout' => 'vertical',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_657991558d512',
							'label' => 'Media Option',
							'name' => 'split_option',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'image' => 'Image',
								'video' => 'Video',
								'embed' => 'Embed Script',
							),
							'default_value' => '',
							'return_format' => 'array',
							'allow_null' => 0,
							'other_choice' => 0,
							'layout' => 'vertical',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_65733f46e8e3e',
							'label' => 'Image',
							'name' => 'split_img',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_657991558d512',
										'operator' => '==',
										'value' => 'image',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_6597fd0e5a33b',
							'label' => 'Image Fit',
							'name' => 'split_fit',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_657991558d512',
										'operator' => '==',
										'value' => 'image',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'cover' => 'Cover',
								'contain' => 'Contain',
							),
							'default_value' => 'cover',
							'return_format' => 'array',
							'allow_null' => 0,
							'other_choice' => 0,
							'layout' => 'vertical',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_65733f46e8e3f',
							'label' => 'Video',
							'name' => 'split_video',
							'aria-label' => '',
							'type' => 'file',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_657991558d512',
										'operator' => '==',
										'value' => 'video',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_65733f46e8e41',
							'label' => 'Video Poster',
							'name' => 'split_poster',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_657991558d512',
										'operator' => '==',
										'value' => 'video',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_65733f46e8e40',
							'label' => 'Embed Script',
							'name' => 'split_embed',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => 'Use for Youtube embed code or comparission shortcode ([comparison before="304" after="304"])',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_657991558d512',
										'operator' => '==',
										'value' => 'embed',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_65733f46e8e42',
							'label' => 'Body Text',
							'name' => 'split_body',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'parent_repeater' => 'field_6373bbcf381ef',
				),
				array(
					'key' => 'field_64f993b0bf112',
					'label' => 'Quicklinks Section',
					'name' => 'quicklinks_section',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6373bc16381f0',
								'operator' => '==',
								'value' => 'quicklinks',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'parent_repeater' => 'field_6373bbcf381ef',
					'sub_fields' => array(
						array(
							'key' => 'field_64f993b0bf113',
							'label' => 'Hide Section?',
							'name' => 'quicklinks_hide',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_654e3fc68a1fb',
							'label' => 'Spacing',
							'name' => 'quicklinks_spacing',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								't' => 'Top',
								'b' => 'Bottom',
							),
							'default_value' => array(
								0 => 't',
								1 => 'b',
							),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 1,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
						),
						array(
							'key' => 'field_64f9a63f9bf68',
							'label' => 'Select Pages/Posts',
							'name' => 'quicklinks_object',
							'aria-label' => '',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'treatments',
								1 => 'page',
							),
							'post_status' => '',
							'taxonomy' => '',
							'return_format' => 'object',
							'multiple' => 1,
							'allow_null' => 0,
							'bidirectional' => 0,
							'ui' => 1,
							'bidirectional_target' => array(
							),
						),
					),
				),
				array(
					'key' => 'field_637e4ebd9885a',
					'label' => 'Accordion Section',
					'name' => 'accordion_section',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6373bc16381f0',
								'operator' => '==',
								'value' => 'accordion',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'parent_repeater' => 'field_6373bbcf381ef',
					'sub_fields' => array(
						array(
							'key' => 'field_63d7b2b294412',
							'label' => 'Hide Section?',
							'name' => 'accordion_hide',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_659d71f9f05e3',
							'label' => 'Spacing',
							'name' => 'accordion_spacing',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								't' => 'Padding Top',
								'b' => 'Padding Bottom',
							),
							'default_value' => array(
								0 => 't',
								1 => 'b',
							),
							'return_format' => 'value',
							'allow_custom' => 0,
							'layout' => 'vertical',
							'toggle' => 1,
							'save_custom' => 0,
							'custom_choice_button_text' => 'Add new choice',
						),
						array(
							'key' => 'field_637e4ebd9885b',
							'label' => 'Heading',
							'name' => 'accordion_heading',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_637e521a3d303',
							'label' => 'List',
							'name' => 'accordion_list',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'row',
							'pagination' => 0,
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_637e525b3d304',
									'label' => 'Title',
									'name' => 'accordion_title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_637e521a3d303',
								),
								array(
									'key' => 'field_637e526a3d305',
									'label' => 'Description',
									'name' => 'accordion_description',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'text',
									'media_upload' => 0,
									'toolbar' => 'full',
									'delay' => 0,
									'parent_repeater' => 'field_637e521a3d303',
								),
							),
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'treatments',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6597db0c6ff82',
	'title' => 'Treatment Page Options',
	'fields' => array(
		array(
			'key' => 'field_6597db0c73b63',
			'label' => 'Alternative title',
			'name' => 'treatment_archive_alt',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6597db0c73b9b',
			'label' => 'Introduction',
			'name' => 'treatment_archive_intro',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_659d40d8c5249',
			'label' => 'Call to actions',
			'name' => 'treatment_archive_btn',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_659d40d8c524a',
					'label' => 'Button Link',
					'name' => 'treatment_archive_btn_link',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_659d40d8c5249',
				),
				array(
					'key' => 'field_659d40d8c524b',
					'label' => 'Button Text',
					'name' => 'treatment_archive_btn_txt',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_659d40d8c5249',
				),
				array(
					'key' => 'field_659d40d8c524c',
					'label' => 'Button Colour',
					'name' => 'treatment_archive_btn_color',
					'aria-label' => '',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'black' => 'Black',
						'accent' => 'Accent',
					),
					'default_value' => 'black',
					'return_format' => 'array',
					'allow_null' => 0,
					'other_choice' => 0,
					'layout' => 'vertical',
					'save_other_choice' => 0,
					'parent_repeater' => 'field_659d40d8c5249',
				),
				array(
					'key' => 'field_659d40d8c524d',
					'label' => 'Button Destination',
					'name' => 'treatment_archive_btn_destination',
					'aria-label' => '',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'internal' => 'Internal',
						'external' => 'External',
					),
					'default_value' => 'internal',
					'return_format' => 'array',
					'allow_null' => 0,
					'other_choice' => 0,
					'layout' => 'vertical',
					'save_other_choice' => 0,
					'parent_repeater' => 'field_659d40d8c5249',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-treatments-page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );

